Repository ocaml-sf/learn-ocaml, pull requests merged in 2021-09, with the labels that each got.

#411 QoL: reset the toplevel every time before evaluating code from the editor
  src/app/learnocaml_common.ml
Labels: kind: enhancement

#409 Move the toplevel buttons to the bottom-right
  static/css/learnocaml_exercise.css
  static/css/learnocaml_main.css
  static/exercise.html
Labels: kind: enhancement, part: CSS

#420 Blacklist jsoo version 3.10.0
  learn-ocaml.opam
Labels: kind: fix

#410 Discourage redundant token creation from users
  src/app/learnocaml_index_main.ml
  static/css/learnocaml_main.css
  static/index.html
  translations/fr.po
Labels: kind: enhancement

#403 Add a ppx facility to test expressions
  src/grader/dune
  src/ppx-metaquot/ppx_metaquot.ml
Labels: feature

#422 fix(CI): Use ocaml 4.12.1
  .ci-macosx.sh
  .github/workflows/static-builds.yml
  learn-ocaml-client.opam
  learn-ocaml-client.opam.locked
  learn-ocaml.opam
  learn-ocaml.opam.locked
  scripts/static-build.sh
Labels: kind: fix, kind: infrastructure

#404 Doc: make accessible the documentation generated by odoc.
  .gitignore
  Makefile
  docs/howto-setup-exercise-development-environment.md
  src/app/learnocaml_common.mli
  src/app/learnocaml_config.ml
  src/app/learnocaml_config.mli
  src/dune
  src/grader/test_lib.mli
  src/index.mld
  src/state/learnocaml_data.mli
  src/toplevel/learnocaml_toplevel.mli
  src/toplevel/learnocaml_toplevel_worker_caller.mli
Labels: kind: fix, kind: documentation

#425 Make find_binding match annotated declarations
  src/grader/test_lib.ml
  tests/test_find_binding/find_binding/annot_all.ml
  tests/test_find_binding/find_binding/annot_all.ml.json
  tests/test_find_binding/find_binding/annot_arg.ml
  tests/test_find_binding/find_binding/annot_arg.ml.json
  tests/test_find_binding/find_binding/annot_ret.ml
  tests/test_find_binding/find_binding/annot_ret.ml.json
  tests/test_find_binding/find_binding/function.ml
  tests/test_find_binding/find_binding/function.ml.json
  tests/test_find_binding/find_binding/simple.ml
  tests/test_find_binding/find_binding/simple.ml.json
  tests/test_find_binding/find_binding/simple2.ml
  tests/test_find_binding/find_binding/simple2.ml.json
  tests/test_find_binding/repo/exercises/find_binding/descr.html
  tests/test_find_binding/repo/exercises/find_binding/meta.json
  tests/test_find_binding/repo/exercises/find_binding/prelude.ml
  tests/test_find_binding/repo/exercises/find_binding/prepare.ml
  tests/test_find_binding/repo/exercises/find_binding/solution.ml
  tests/test_find_binding/repo/exercises/find_binding/template.ml
  tests/test_find_binding/repo/exercises/find_binding/test.ml
  tests/test_find_binding/repo/exercises/index.json
Labels: kind: enhancement

#393 feat: Make the prelude available in description page
  src/app/learnocaml_common.ml
  src/app/learnocaml_common.mli
  src/app/learnocaml_description_main.ml
  static/css/learnocaml_description.css
  static/description.html
Labels: kind: enhancement

#423 feat: Improve description entrypoint
  src/app/learnocaml_description_main.ml
  static/css/learnocaml_description.css
  static/description.html
Labels: kind: enhancement, needs: merge of dependency

#426 feat: Relax the client/server coupling & Add support for API versioning
  dune-project
  learn-ocaml-client.opam
  learn-ocaml-client.opam.locked
  learn-ocaml.opam
  learn-ocaml.opam.locked
  src/main/learnocaml_client.ml
  src/state/learnocaml_api.ml
  src/state/learnocaml_api.mli
Labels: feature

#421 docs: Document student answers classification
  docs/howto-classify-students-answers.md
  docs/index.md
Labels: kind: documentation

#427 docs: Improve the new text of the old "API version mismatch" error
  src/main/learnocaml_client.ml
Labels: kind: documentation
