Repository ocaml-sf/learn-ocaml, pull requests merged in 2021-07, with the labels that each got.

#401 GitHub: create issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: enhancement

#406 fix: better error msg for X-token registration
  src/state/learnocaml_store.ml
Labels: fix

#391 Add github action rules for static binaries generation (Linux, Macos)
  .ci-macosx.sh
  .github/workflows/static-builds.yml
  .gitignore
  Makefile
  learn-ocaml-client.opam
  learn-ocaml.opam
  scripts/static-build.sh
  src/main/dune
  src/main/linking_flags.sh
Labels: feature
