Repository ocaml-sf/learn-ocaml, pull requests merged in 2022-03, with the labels that each got.

#469 feat: Build `learn-ocaml-www.zip` → `learn-ocaml --contents-dir=www`
  .github/workflows/release.yml
  .github/workflows/static-builds.yml
Labels: feature

#468 chore: Update maintainer list & Add our e-mail address
  learn-ocaml-client.opam
  learn-ocaml-client.opam.locked
  learn-ocaml.opam
  learn-ocaml.opam.locked
Labels: kind: documentation

#372 Offer better protections against solution overwriting
  src/ace-lib/ace.ml
  src/ace-lib/ace.mli
  src/ace-lib/ocaml_mode.ml
  src/ace-lib/ocaml_mode.mli
  src/app/learnocaml_common.ml
  src/app/learnocaml_common.mli
  src/app/learnocaml_exercise_main.ml
  src/app/learnocaml_index_main.ml
  src/app/learnocaml_playground_main.ml
  translations/fr.po
Labels: feature

#474 fix: Change `learn-ocaml-www.zip` inner dir (`www` → `learn-ocaml-www`)
  .github/workflows/static-builds.yml
Labels: kind: fix
