Repository ocaml-sf/learn-ocaml, pull requests merged in 2023-05, with the labels that each got.

#540 Hide tokens in partition-view.html
  src/app/learnocaml_partition_view.ml
  static/css/learnocaml_common.css
  static/css/learnocaml_partition_view.css
  static/partition-view.html
Labels: kind: feature

#544 ci(docker): Use docker/build-push-action@v4
  .github/workflows/deploy-master.yml
  .github/workflows/release.yml
Labels: kind: infrastructure

#547 Don't prefix URLs starting with `https?://` at `learn-ocaml build` time
  src/main/learnocaml_main.ml
  static/css/learnocaml_common.css
  static/css/learnocaml_partition_view.css
Labels: kind: bug, kind: cleanup

#551 ci(docker): Replace `LABEL` Dockerfile commands with `labels:` (GHA)
  .github/workflows/deploy-master.yml
  .github/workflows/release.yml
  Dockerfile
Labels: kind: cleanup
