Repository ocaml-sf/learn-ocaml, pull requests merged in 2023-10, with the labels that each got.

#565 chore(macos): Fix `brew upgrade` failure
  .ci-macosx.sh
Labels: kind: infrastructure

#564 feat(UI): Add possibility to choose exercise display order
  src/app/learnocaml_index_main.ml
  src/state/learnocaml_data.ml
  src/state/learnocaml_data.mli
  static/css/learnocaml_main.css
  translations/fr.po
Labels: kind: feature

#566 Teacher tab: fix the Closed/Open state handling
  src/app/learnocaml_teacher_tab.ml
  src/state/learnocaml_data.ml
  src/state/learnocaml_data.mli
  src/state/learnocaml_data_test.ml
Labels: kind: fix
