Repository ocaml-sf/learn-ocaml, pull requests merged in 2023-11, with the labels that each got.

#571 ci(*.yml): Move opam-publish in a separate workflow to enable testing (bis)
  .github/workflows/opam-publish.yml
  .github/workflows/release.yml
  .github/workflows/test-opam-publish.yml
  scripts/opam-publish.exp
Labels: kind: enhancement, kind: infrastructure, kind: test

#568 fix(grading): avoid failing on sampling arrays with unique elements
  src/grader/test_lib.ml
  src/grader/test_lib.mli
Labels: kind: fix

#567 feat(server): add a `--replace` option
  src/main/learnocaml_main.ml
  src/main/learnocaml_server_args.ml
  src/main/learnocaml_server_args.mli
  src/main/learnocaml_server_main.ml
  src/repo/learnocaml_process_exercise_repository.ml
  src/server/learnocaml_server.ml
  src/server/learnocaml_server.mli
Labels: kind: feature
