Repository ocaml-sf/learn-ocaml, pull requests merged in 2024-02, with the labels that each got.

#582 fix(UI): Small CSS fix for exercise lists on small screens
  static/css/learnocaml_main.css
Labels: part: CSS, kind: fix

#584 fix: do exercise recompilation correctly with `--replace`
  src/utils/lwt_utils.ml
Labels: kind: fix

#585 feat: Add CLI option `learn-ocaml build --build-dir=[./learn-ocaml-build]`
  src/main/learnocaml_main.ml
Labels: kind: enhancement

#586 chore(test-opam-publish.yml): Update preflight workflow
  .github/workflows/test-opam-publish.yml
Labels: kind: infrastructure
